version: '3.0'

services:
  nest-app:
    container_name: nest-app
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4000:4000
      - 9229:9229
    environment:
      VIRTUAL_HOST: megasaab98.com
      VIRTUAL_PORT: 4000
      LETSENCRYPT_HOST: megasaab98.com
    command: npm run start:prod
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: root
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:

networks:
  https:
    external:
      name: https_network
