version: '3.0'

services:
  nest-app:
    container_name: nest-app
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4000:4000
      - 9229:9229
    environment:
      VIRTUAL_HOST: ${SSL_DOMAIN}
      VIRTUAL_PORT: ${NEST_PORT}
      LETSENCRYPT_HOST: ${SSL_DOMAIN}
    command: npm run start:prod
    restart: always

networks:
  https:
    external:
      name: https_network
